### PR TITLE
Fix potential kernel‐stack OOB read in 'p_ed_enforce_pcfi'

### LINKED ISSUE #450: Potential (unreachable?) Out-of-bounds kernel‐stack read in 'p_ed_enforce_pcfi()'
Depends on various CONFIG options `p_ed_enforce_pcfi()` walks a task’s stack in various ways. If there is no defined CONFIG_UNWINDER_ORC we manually extract the metadata from the current frame pointer (`p_fp`). However, if the frame pointer is sitting on the end of stack (probably not possible in normal case scenarios) then we insufficiently verify the boundaries in `p_is_obj_on_stack` function by checking if `p_fp` points *somewhere* inside the task’s stack:
 ```
if ((unsigned long)p_fp < p_regs_get_sp(p_regs) || !p_is_obj_on_stack(p_task, p_fp))
        break;
```
`p_is_obj_on_stack()` is defined as:
```
tatic inline int p_is_obj_on_stack(struct task_struct *p_task, const void *p_addr)
 {
     void *p_stack = p_task->stack;
     return (p_addr >= p_stack) && (p_addr < (p_stack + THREAD_SIZE));
 }
```
but we does not ensure that the entire metadata (and on X86 without CONFIG_UNWINDER_ORC entire `struct stack_frame`) fits inside the stack bounds. 
**I don't think it possibly to ever hit that in normal scenario since it's the kernel stack (not user-mode) and kernel itself must fit the metadata inside the stack too.** However, for the correctness I think we should address it.
The fix is simple (I tested it) by introducing 3rd parameter for `p_is_obj_on_stack` describing the size of how much data we need to read. Every caller of it needs to provide a proper and desired value.

### PR DESCRIPTION
**Pull request by Adam-pi3**
This bug is unlikely to be reachable; otherwise, the kernel would hit the same bug. However, for correctness, we should still address it.

Fixes #450.

### How Has This Been Tested?
Run LKRG for a few hours

### CODE REVIEW

File: src/modules/exploit_detection/p_exploit_detection.c [hunk 1]
```diff
@@ -1569,7 +1569,12 @@ int p_ed_enforce_pcfi(struct task_struct *p_task, struct p_ed_process *p_orig, s
       goto p_ed_enforce_pcfi_out;
 
 #ifndef CONFIG_UNWINDER_ORC
-   if (!p_is_obj_on_stack(p_task, p_fp)) {
+   if (!p_is_obj_on_stack(p_task, p_fp,
+#if defined(CONFIG_ARM) || defined(CONFIG_X86_32)
+ 4 )) {
+#else
+ 8 )) {
+#endif
```
Comment (solardiz) [inline src/modules/exploit_detection/p_exploit_detection.c]: Inconsistent indentation, and I think should simply use `sizeof(void *)`.

**Comment by solardiz** [comment]
Two CI jobs are failing, here's one of them:

```
[   65.846291] BUG: unable to handle page fault for address: ffffffffffffffff
[   65.850473] #PF: supervisor read access in kernel mode
[   65.850862] #PF: error_code(0x0000) - not-present page
[   65.851352] PGD 1ce44067 P4D 1ce45067 PUD 1ce47067 PMD 0 
[   65.852441] Oops: Oops: 0000 [#1] PREEMPT SMP NOPTI
[   65.853174] CPU: 0 UID: 0 PID: 451 Comm: systemd Tainted: G           OE      6.14.0-37-generic #37-Ubuntu
[   65.853970] Tainted: [O]=OOT_MODULE, [E]=UNSIGNED_MODULE
[   65.854259] Hardware name: QEMU Standard PC (Q35 + ICH9, 2009), BIOS 0.0.0 02/06/2015
[   65.854861] RIP: 0010:p_ed_enforce_pcfi+0x13e/0x400 [lkrg]
[   65.855855] Code: 85 28 fd ff ff 00 00 00 00 4d 3b be 98 00 00 00 72 67 48 8b 43 20 49 39 c7 72 5e 49 8d 57 10 48 05 00 40 00 00 48 39 c2 73 4f <49> 8b 07 48 89 85 20 fd ff ff 49 8b 47 08 48 89 85 28 fd ff ff 48
[   65.857016] RSP: 0000:ff855e60808ffa78 EFLAGS: 00000207
[   65.857411] RAX: ff855e6080900000 RBX: ff3be26ec3e20000 RCX: 0000000000000000
[   65.857844] RDX: 000000000000000f RSI: 0000000000000000 RDI: 0000000000000000
[   65.858251] RBP: ff855e60808ffd80 R08: 0000000000000000 R09: 0000000000000000
[   65.858656] R10: ff3be26eca321860 R11: 0000000000000005 R12: ff3be26eca341420
[   65.859067] R13: 0000000000000000 R14: ff855e60808ffe00 R15: ffffffffffffffff
[   65.859561] FS:  00007c7cd825bdc0(0000) GS:ff3be26efc200000(0000) knlGS:0000000000000000
[   65.860001] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   65.860342] CR2: ffffffffffffffff CR3: 0000000005151000 CR4: 00000000007516f0
[   65.860891] PKRU: 55555554
[   65.861139] Call Trace:
[   65.861730]  <TASK>
[   65.862219]  ? xa_load+0x73/0xb0
[   65.862859]  p_pcfi_schedule_entry+0xad/0x1a0 [lkrg]
[   65.863287]  ? __pfx_schedule+0x10/0x10
[   65.863500]  kprobe_ftrace_handler+0x155/0x1e0
[   65.863763]  ? schedule+0x5/0xd0
[   65.864000]  0xffffffffc06930f5
[   65.864480] RIP: 0010:schedule+0x1/0xd0
[   65.864690] Code: c7 c7 30 e3 e8 8a e8 fe d8 74 ff e9 7f fa ff ff 66 0f 1f 84 00 00 00 00 00 90 90 90 90 90 90 90 90 90 90 90 90 90 90 90 90 e8 <db> 87 95 36 55 48 89 e5 41 54 53 65 48 8b 1d 0c ba 2f 76 8b 43 18
[   65.865466] RSP: 0018:ff855e60808ffee0 EFLAGS: 00000202 ORIG_RAX: 0000000000000000
[   65.865845] RAX: 0000000000000000 RBX: 0000000000000008 RCX: 0000000000000000
[   65.866173] RDX: 0000000000000000 RSI: 0000000000000000 RDI: ff855e60808fff48
[   65.866504] RBP: ff855e60808fff00 R08: 0000000000000000 R09: 0000000000000000
[   65.866838] R10: 0000000000000000 R11: 0000000000000000 R12: ff3be26ec3e20000
[   65.867239] R13: ff855e60808fff48 R14: 0000000000000000 R15: 0000000000000000
[   65.867613]  ? schedule+0x5/0xd0
[   65.867781]  ? irqentry_exit_to_user_mode+0x109/0x1d0
[   65.868026]  ? schedule+0x5/0xd0
[   65.868205]  ? irqentry_exit_to_user_mode+0x109/0x1d0
[   65.868453]  irqentry_exit+0x43/0x50
[   65.868636]  sysvec_apic_timer_interrupt+0x57/0xc0
[   65.868894]  asm_sysvec_apic_timer_interrupt+0x1b/0x20
[   65.869175] RIP: 0033:0x7c7cd845d618
[   65.869550] Code: c4 20 e9 82 fe ff ff 66 66 2e 0f 1f 84 00 00 00 00 00 f3 0f 1e fa 48 8b 77 08 48 8b 07 48 85 f6 75 08 c3 0f 1f 80 00 00 00 00 <48> 89 c7 e9 60 51 ff ff f3 0f 1e fa 55 48 89 e5 53 48 83 ec 08 48
[   65.870429] RSP: 002b:00007fffc4678488 EFLAGS: 00000202
[   65.870721] RAX: 000000000000000f RBX: 00005af332683000 RCX: 0000000000000001
[   65.871045] RDX: 00000005af3326b0 RSI: 0000000000000064 RDI: 00005af3326834e8
[   65.871344] RBP: 00007fffc4678570 R08: 00007c7cd7c11ac0 R09: 0000000000000000
[   65.871655] R10: 0000000000000000 R11: 0000000000000297 R12: 00007fffc46784e0
[   65.871922] R13: ffffffffffffffff R14: ffffffffffffffff R15: ffffffffffffffff
[   65.872313]  </TASK>
[   65.872530] Modules linked in: input_leds mac_hid cfg80211 sch_fq_codel efi_pstore nfnetlink ip_tables x_tables polyval_generic ghash_clmulni_intel sha256_ssse3 ahci psmouse sha1_ssse3 libahci serio_raw lkrg(OE) dmi_sysfs qemu_fw_cfg virtio_rng autofs4 aesni_intel crypto_simd cryptd
[   65.874140] CR2: ffffffffffffffff
[   65.874683] ---[ end trace 0000000000000000 ]---
[   66.398639] RIP: 0010:p_ed_enforce_pcfi+0x13e/0x400 [lkrg]
[   66.399029] Code: 85 28 fd ff ff 00 00 00 00 4d 3b be 98 00 00 00 72 67 48 8b 43 20 49 39 c7 72 5e 49 8d 57 10 48 05 00 40 00 00 48 39 c2 73 4f <49> 8b 07 48 89 85 20 fd ff ff 49 8b 47 08 48 89 85 28 fd ff ff 48
[   66.399751] RSP: 0000:ff855e60808ffa78 EFLAGS: 00000207
[   66.400032] RAX: ff855e6080900000 RBX: ff3be26ec3e20000 RCX: 0000000000000000
[   66.400369] RDX: 000000000000000f RSI: 0000000000000000 RDI: 0000000000000000
[   66.400698] RBP: ff855e60808ffd80 R08: 0000000000000000 R09: 0000000000000000
[   66.401031] R10: ff3be26eca321860 R11: 0000000000000005 R12: ff3be26eca341420
ABORT
[   66.401368] R13: 0000000000000000 R14: ff855e60808ffe00 R15: ffffffffffffffff
[   66.401677] FS:  00007c7cd825bdc0(0000) GS:ff3be26efc200000(0000) knlGS:0000000000000000
[   66.402113] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   66.402390] CR2: ffffffffffffffff CR3: 0000000005151000 CR4: 00000000007516f0
[   66.402705] PKRU: 55555554
[   66.403094] Kernel panic - not syncing: Fatal exception
[   66.404039] Kernel Offset: 0x7800000 from 0xffffffff81000000 (relocation range: 0xffffffff80000000-0xffffffffbfffffff)
```

**Comment by solardiz** [comment]
The other is similar:

```
[   90.075865] BUG: unable to handle page fault for address: ffffffffffffffff
[   90.079916] #PF: supervisor read access in kernel mode
[   90.080314] #PF: error_code(0x0000) - not-present page
[   90.080758] PGD 1ac40067 P4D 1ac41067 PUD 1ac43067 PMD 0 
[   90.081770] Oops: 0000 [#1] PREEMPT SMP NOPTI
[   90.082313] CPU: 0 PID: 510 Comm: systemd Tainted: G           OE      6.8.0-90-generic #91-Ubuntu
[   90.082888] Hardware name: QEMU Standard PC (Q35 + ICH9, 2009), BIOS 0.0.0 02/06/2015
[   90.083430] RIP: 0010:p_ed_enforce_pcfi+0x3d4/0x660 [lkrg]
[   90.084431] Code: f2 48 c7 c7 70 28 38 c0 4c 89 95 18 fd ff ff e8 c2 89 e5 cb e8 8d 3d ff ff 4c 8b 95 18 fd ff ff b8 01 00 00 00 e9 fe fd ff ff <49> 8b 55 00 48 89 95 20 fd ff ff 49 8b 55 08 48 89 95 28 fd ff ff
[   90.085415] RSP: 0000:ff7aa7aa4037baa0 EFLAGS: 00000207
[   90.085787] RAX: 0000000000000000 RBX: ff2eae7eb3108000 RCX: 0000000000000005
[   90.086160] RDX: ff7aa7aa4037c000 RSI: 000000000000000f RDI: 0000000000000000
[   90.086481] RBP: ff7aa7aa4037bda0 R08: 0000000000000000 R09: 0000000000000000
[   90.086819] R10: ff2eae7e89532208 R11: 0000000000000000 R12: ff2eae7e895f9948
[   90.087175] R13: ffffffffffffffff R14: ff7aa7aa4037bad6 R15: ff7aa7aa4037be18
[   90.087601] FS:  00007e6a7959b940(0000) GS:ff2eae7ebc200000(0000) knlGS:0000000000000000
[   90.088022] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   90.088323] CR2: ffffffffffffffff CR3: 00000000082a6000 CR4: 00000000007516f0
[   90.088805] PKRU: 55555554
[   90.089073] Call Trace:
[   90.089610]  <TASK>
[   90.090079]  ? __memcg_slab_free_hook+0x115/0x180
[   90.090700]  p_pcfi_schedule_entry+0xb9/0x430 [lkrg]
[   90.091084]  ? schedule+0x1/0x110
[   90.091297]  kprobe_ftrace_handler+0x146/0x270
[   90.091558]  ? schedule+0x5/0x110
[   90.091788]  0xffffffffc03980f7
[   90.092216] RIP: 0010:schedule+0x1/0x110
[   90.092438] Code: f5 48 c7 c7 b0 34 69 8e e8 3c 0d 6f ff e9 1f fa ff ff 0f 1f 80 00 00 00 00 90 90 90 90 90 90 90 90 90 90 90 90 90 90 90 90 e8 <5b> 64 14 33 55 48 89 e5 41 54 53 65 48 8b 1c 25 00 42 03 00 8b 43
[   90.093247] RSP: 0018:ff7aa7aa4037bef8 EFLAGS: 00000202 ORIG_RAX: 0000000000000000
[   90.093600] RAX: 0000000000000000 RBX: 0000000000000008 RCX: 0000000000000000
[   90.093909] RDX: 0000000000000000 RSI: 0000000000000000 RDI: ff7aa7aa4037bf58
[   90.094235] RBP: ff7aa7aa4037bf18 R08: 0000000000000000 R09: 0000000000000000
[   90.094539] R10: 0000000000000000 R11: 0000000000000000 R12: ff2eae7eb3108000
[   90.094862] R13: ff7aa7aa4037bf58 R14: 0000000000000000 R15: 0000000000000000
[   90.095296]  ? schedule+0x5/0x110
[   90.095483]  ? irqentry_exit_to_user_mode+0x11e/0x1e0
[   90.095723]  ? schedule+0x5/0x110
[   90.095890]  ? irqentry_exit_to_user_mode+0x11e/0x1e0
[   90.096142]  irqentry_exit+0x43/0x50
[   90.096324]  sysvec_apic_timer_interrupt+0x4b/0xd0
[   90.096554]  asm_sysvec_apic_timer_interrupt+0x1b/0x20
[   90.096814] RIP: 0033:0x7e6a793ce949
[   90.097124] Code: 9b 48 8d 0d b9 d3 14 00 ba 64 00 00 00 48 8d 35 6f 5b 0f 00 48 8d 3d 86 28 0f 00 e8 c1 c8 ff ff 90 f3 0f 1e fa 48 85 ff 74 37 <55> 48 89 e5 41 54 49 89 f4 53 48 89 fb 48 39 f7 74 55 48 85 f6 74
[   90.097860] RSP: 002b:00007ffc15c049d8 EFLAGS: 00000206
[   90.098133] RAX: 000000000000000f RBX: 00006182335560f0 RCX: 0000000000000001
[   90.098462] RDX: 0000000618233576 RSI: 0000000000000064 RDI: 000000000000000f
[   90.098772] RBP: 00007ffc15c04ac0 R08: 0000618233551010 R09: 0000000000000007
[   90.099099] R10: 00006182335768d0 R11: e470b34b5716e64d R12: 00007ffc15c04a30
[   90.099423] R13: ffffffffffffffff R14: ffffffffffffffff R15: ffffffffffffffff
[   90.099754]  </TASK>
[   90.099951] Modules linked in: kvm_amd ccp kvm psmouse irqbypass lpc_ich i2c_i801 i2c_smbus cfg80211 input_leds mac_hid efi_pstore nfnetlink dmi_sysfs ip_tables x_tables crct10dif_pclmul crc32_pclmul polyval_generic ghash_clmulni_intel sha256_ssse3 ahci sha1_ssse3 libahci serio_raw lkrg(OE) dm_mirror dm_region_hash dm_log qemu_fw_cfg virtio_rng autofs4 aesni_intel crypto_simd cryptd
[   90.101860] CR2: ffffffffffffffff
[   90.102349] ---[ end trace 0000000000000000 ]---
[   90.598058] RIP: 0010:p_ed_enforce_pcfi+0x3d4/0x660 [lkrg]
[   90.598451] Code: f2 48 c7 c7 70 28 38 c0 4c 89 95 18 fd ff ff e8 c2 89 e5 cb e8 8d 3d ff ff 4c 8b 95 18 fd ff ff b8 01 00 00 00 e9 fe fd ff ff <49> 8b 55 00 48 89 95 20 fd ff ff 49 8b 55 08 48 89 95 28 fd ff ff
[   90.599258] RSP: 0000:ff7aa7aa4037baa0 EFLAGS: 00000207
[   90.599513] RAX: 0000000000000000 RBX: ff2eae7eb3108000 RCX: 0000000000000005
[   90.599804] RDX: ff7aa7aa4037c000 RSI: 000000000000000f RDI: 0000000000000000
[   90.600129] RBP: ff7aa7aa4037bda0 R08: 0000000000000000 R09: 0000000000000000
[   90.600448] R10: ff2eae7e89532208 R11: 0000000000000000 R12: ff2eae7e895f9948
ABORT
[   90.600769] R13: ffffffffffffffff R14: ff7aa7aa4037bad6 R15: ff7aa7aa4037be18
[   90.601108] FS:  00007e6a7959b940(0000) GS:ff2eae7ebc200000(0000) knlGS:0000000000000000
[   90.601454] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   90.601766] CR2: ffffffffffffffff CR3: 00000000082a6000 CR4: 00000000007516f0
[   90.602267] PKRU: 55555554
[   90.602624] Kernel panic - not syncing: Fatal exception
[   90.603508] Kernel Offset: 0xb000000 from 0xffffffff81000000 (relocation range: 0xffffffff80000000-0xffffffffbfffffff)
```

**Comment by Adam-pi3** [comment]
@solardiz yeah I saw that. It's a bit puzzle to me how this changes can trigger it since we are making the checks even more restrict than before. It could be that the problem is not related to the changes but something else is just visible now.
It will be difficult to root-cause it without debugging environment. @solardiz @vt-alt do you know if it is possible to get some kind of remote shell/debugging to this CI session to be able to live debug it? Another option maybe we can enable  higher log_level during debug run? What other options we have?

**Comment by Adam-pi3** [comment]
OK, I found some time and confirmed that this specific problem is unrelated to this patch. I installed the same machine with the same configuration and install LKRG to be loaded during boot. The same problem is issued without this PR. Moreover, the problem is only visible when LKRG is loaded during booting process. After boot, that's not visible. When I find some more time I will try to dig in which patch/diff introduce the problem and what is the problem - unless someone else have more time to do it faster CC: @solardiz @kerneltoast

**Comment by solardiz** [comment]
> The same problem is issued without this PR. Moreover, the problem is only visible when LKRG is loaded during booting process.

Well, but we had this same test run on these same(?) versions of Ubuntu for months, including most recently when you pushed your sysctl locking fix this month. So it's puzzling the problem didn't occur there, but did here and does in your local testing. I think we don't know everything we'd have liked to know about this yet.

**Comment by Adam-pi3** [comment]
It is some type of race as you can see here only 1 instance failed. You must hit specific transition and i see it is usually hit when booting is finished and it is switch to login page. I could almost 100% hit reliably this problem until this commit:

36b46181aa23cf4c89eb1d2ca8c9c83a9436a6cb

This commit is not hitting as reliably the problem (it still does, but not 100% time)

**Comment by solardiz** [comment]
> It is some type of race as you can see here only 1 instance failed.

Yes. I re-ran those two jobs after your previous comment, and only 1 of them failed.

**Comment by solardiz** [comment]
I wonder if it's maybe some backport that's been made recently into kernels (or gcc or something else?) on those older versions of Ubuntu, which are LTS and still maintained.

**Comment by Adam-pi3** [comment]
I think it's actually more complicated, the one issue which is so reliable is actually problem with freezing the tasks not CFI crash itself.

> I wonder if it's maybe some backport that's been made recently into kernels (or gcc or something else?) on those older versions of Ubuntu, which are LTS and still maintained.

Could be. I'm not sure I would be able to synthetically catch the similar problem (not the freezing the task one). But maybe we can tune CI to enable DEBUG build with more verbose logs to see what's going on on CI

**Comment by solardiz** [comment]
> maybe we can tune CI to enable DEBUG build with more verbose logs to see what's going on on CI

You can try that in your fork of the repo. BTW, we already enable a little bit more debugging in those:

```
$ grep -r DEBUG .github/
.github/workflows/docker-boot.yml:                  sed -i '/P_LKRG_JUMP_LABEL_STEXT_DEBUG/s/\/\///' src/modules/print_log/p_lkrg_print_log.h
.github/workflows/fedora-mainline.yml:                  sed -i '/P_LKRG_JUMP_LABEL_STEXT_DEBUG/s/\/\///' src/modules/print_log/p_lkrg_print_log.h
```

**Comment by solardiz** [comment]
> I re-ran those two jobs after your previous comment, and only 1 of them failed.

I re-ran the one still failing job since, and it failed again. So far it's 3 failures in 3 runs for that job in this PR. While the failures look similar, there's slight variance in `Comm` at the time of failure - `systemd` vs. `systemd-sysuser` - which doesn't mean much as the crashes are in hooks from `schedule`, so not in task context. I now recall that in #184, (a different kind of) failures were also especially common in `schedule` - maybe that's related in the sense that our assumptions about the state of kernel stack in there are wrong?

**Comment by Adam-pi3** [comment]
Interesting. I just made an interesting test on my VM and all the problems disappeared when I masked `systemd-binfmt` service. However, it was related to the conflict of user-mode tasks not being able to fully sleep during initialization. Some ideas which are on my head:
1. Add the following check on hook:
```
	if (!task_is_running(task))
		return;
```
2. Look deeper into UMH <---> schedule() <---> proc/sysctl relationship
3. Curious why we don't do full verification on `schedule()` just pCFI, @solardiz do you happened to know/remember?

**Comment by solardiz** [comment]
> Curious why we don't do full verification on `schedule()` just pCFI, @solardiz do you happened to know/remember?

I don't remember such discussions (nor whether we had any), but I think that would be a paranoid mode thing, not something we want by default if at all.

Rather, I wonder why we bother to check pCFI there at all. It `schedule` isn't likely to be used in a ROP chain, is it?

It makes more sense to me that we check global CPU flags in there, but is this worth having this hook? Knowing you, I think you'd just say yes, but I am unsure.

**Comment by Adam-pi3** [comment]
`schedule()` can be called in the middle of exploitation process (and even in the middle of ROP - depending on the logic). It actually was effective on stopping bypasses. Moreover, it introduces unpredictability and attacker's exploitation process must fit in the window before `schedule()` is invoked (e.g., via sleeping function)

**Comment by Adam-pi3** [comment]
OK, I finally found time to setup debugging environment and properly analyze it. So there is an interesting corner case with IRQ and WQ where a last frame (what is interesting it looks like a valid frame) has IP/FP set to 0xFFFFFFFFFFFFFFFF. Because of newly added more restricted check this would overflow (because we are adding how much we want to read) which would pass both checks on fp<-->sp verification which we had. It actually make sense to add stricter check that FP/SP should never be above defined last kernel unused hole (and that 's what we do now). It fixes the problem on my testing machines. @solardiz it looks like the failing build we have is on the code related to your NET module. Can you check this?

**Comment by solardiz** [comment]
> looks like the failing build we have is on the code related to your NET module. Can you check this?

Hmm, yes. I wonder if ALT is somehow quicker to update to a newer mainline rc kernel than Fedora is? @vt-alt 

```
src/modules/net/net.c: In function 'maybe_reconnect':
src/modules/net/net.c:143:45: error: passing argument 2 of 'sk->ops->connect' from incompatible pointer type [-Wincompatible-pointer-types]
  143 |         switch ((err = sk->ops->connect(sk, (struct sockaddr *)&saddr, sizeof(saddr), O_WRONLY))) {
      |                                             ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                                             |
      |                                             struct sockaddr *
src/modules/net/net.c:143:45: note: expected 'struct sockaddr_unsized *' but argument is of type 'struct sockaddr *'
  CC [M]  src/modules/database/arch/x86/p_switch_idt/p_switch_idt.o
make[4]: *** [/usr/src/linux-6.19.0-6.19-alt0.rc3/scripts/Makefile.build:287: src/modules/net/net.o] Error 1
```

**Comment by Adam-pi3** [comment]
@solardiz can you merge this PR if there is no more feedback? :)

**Comment by solardiz** [comment]
Thank you @Adam-pi3 for investigating this!

> corner case with IRQ and WQ where a last frame (what is interesting it looks like a valid frame) has IP/FP set to 0xFFFFFFFFFFFFFFFF.

Is this reliable, actually implemented that way somewhere in kernel code, or does it just happen to be so in testing so far?

> Because of newly added more restricted check this would overflow (because we are adding how much we want to read) which would pass both checks on fp<-->sp verification which we had. It actually make sense to add stricter check that FP/SP should never be above defined last kernel unused hole (and that 's what we do now).

OK, makes sense.

Code quality wise, I think we don't want `P_KERNEL_LAST_UNUSED_HOLE` in the header file. Just put it in the `.c` file, perhaps near actual use. You had some old convention of putting all macros in header files, but I think that's a bad convention to have. But I don't insist on revising this now, we can clean it up later.

**Comment by solardiz** [comment]
> I wonder if ALT is somehow quicker to update to a newer mainline rc kernel than Fedora is?

Looks so. The Fedora test is still with 6.18.0-65.fc44.x86_64.

**Comment by solardiz** [comment]
> @solardiz can you merge this PR if there is no more feedback? :)

Yes, I can merge it now, unless you want to remove `P_KERNEL_LAST_UNUSED_HOLE` from the header first?

**Comment by Adam-pi3** [comment]
> Yes, I can merge it now, unless you want to remove P_KERNEL_LAST_UNUSED_HOLE from the header first?

I will move it tomorrow - because i think it is also not completely correct since we should differentiate between 32 and 64 bit build - 32 bit kernel should have different value.

**Comment by Adam-pi3** [comment]
@solardiz done

**Comment by solardiz** [comment]
@Adam-pi3 Thanks. Let's merge this. If this were my PR, I think I'd squash these 4 commits into 1 or maybe 2, but I don't mind keeping them as-is.

BTW, the pointer comparisons are strictly speaking UB in C because the pointers are not to within the same object at C level. However, I guess the kernel probably assumes that this just works anyway, and this isn't new with this PR. Also, pointer math on `void *` is a GNU extension anyway.

**Comment by vt-alt** [comment]
> do you know if it is possible to get some kind of remote shell/debugging to this CI session to be able to live debug it?

Btw, AFAIK it is not possible for GA.

> Hmm, yes. I wonder if ALT is somehow quicker to update to a newer mainline rc kernel than Fedora is? @vt-alt

The actual kernel version should be reported in Actions in Annotations panel.

Usually I (manually) update in 1 day, and we follow mainline releases (so it's once per Sunday evening).

Fedora, AFAIK, may delay arbitrarily, skip some releases, or update to random day instead of proper rc release. See (in [kernel-ark](https://gitlab.com/cki-project/kernel-ark) tree):
```
0365c52 2026-01-03 11:22 Fedora Kernel Team     ∙ [os-build] [redhat] kernel-6.19.0-0.rc3.805f9a061372.28
954ca91 2026-01-03 10:28 Fedora Kernel Team     ∙ Merge 'master' into 'os-build'
f67065f 2026-01-02 08:43 Justin M. Forbes       ∙ Merge branch 'feat/bst_config' into 'os-build'
46605e7 2026-01-02 08:39 Justin M. Forbes       ∙ Merge branch 'beagle' into 'os-build'
4691c3f 2026-01-01 11:21 Fedora Kernel Team     ∙ [redhat] kernel-6.19.0-0.rc3.b69053dd3ffb.27
f1125b6 2026-01-01 10:27 Fedora Kernel Team     ∙ Merge 'master' into 'os-build'
61f25da 2025-12-31 11:22 Fedora Kernel Team     ∙ [redhat] kernel-6.19.0-0.rc3.c8ebd433459b.26
0fc7d02 2025-12-31 10:27 Fedora Kernel Team     ∙ Merge 'master' into 'os-build'
cd5ac39 2025-12-30 11:22 Fedora Kernel Team     ∙ [redhat] kernel-6.19.0-0.rc3.8640b74557fc.25
6b937a0 2025-12-30 10:27 Fedora Kernel Team     ∙ Merge 'master' into 'os-build'
c9eb444 2025-12-29 11:25 Fedora Kernel Team     ∙ [redhat] kernel-6.19.0-0.rc3.7839932417dd.24
f37db75 2025-12-29 10:37 Fedora Kernel Team     ∙ Merge 'master' into 'os-build'
f269d66 2025-12-28 11:21 Fedora Kernel Team     ∙ [redhat] kernel-6.19.0-0.rc2.d26143bb38e2.23
8cb3c6c 2025-12-28 10:26 Fedora Kernel Team     ∙ Merge 'master' into 'os-build'
```

For example `kernel-6.19.0-0.rc3.7839932417dd.24` is NOT `v6.19-rc3` but next day of it when Linus already pulled 3 more pull requests into `master`.

Not all of these release tags reach Fedora package repo, though. Currently, latest package is `6.18.0-65`, I guess, the git tag is `kernel-6.18.0-65` there (it's 2025-12-01). I don't know the internal workings of Fedora package release process.

**Comment by solardiz** [comment]
Thank you @vt-alt! I am now dealing with 6.19 portability issues in #452.
