### PR TITLE
Fix build for 6.19+

### LINKED ISSUE #452: Build failures on 6.19
```
src/modules/net/net.c: In function 'maybe_reconnect':
src/modules/net/net.c:143:45: error: passing argument 2 of 'sk->ops->connect' from incompatible pointer type [-Wincompatible-pointer-types]
  143 |         switch ((err = sk->ops->connect(sk, (struct sockaddr *)&saddr, sizeof(saddr), O_WRONLY))) {
      |                                             ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                                             |
      |                                             struct sockaddr *
src/modules/net/net.c:143:45: note: expected 'struct sockaddr_unsized *' but argument is of type 'struct sockaddr *'
  CC [M]  src/modules/database/arch/x86/p_switch_idt/p_switch_idt.o
make[4]: *** [/usr/src/linux-6.19.0-6.19-alt0.rc3/scripts/Makefile.build:287: src/modules/net/net.o] Error 1
```

### PR DESCRIPTION
**Pull request by solardiz**
### Description

Cast to the new (struct sockaddr_unsized *) on 6.19+. Use in_hardirq() in preference of the obsolete in_irq().

Fixes #452

### How Has This Been Tested?

In our CI setup only so far.

### CODE REVIEW

**Comment by solardiz** [comment]
The one failed test here is:

```
  #7 50.31 Fetched 487 MB in 25s (19.3 MB/s)
  #7 50.31 E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/pool/restricted/f/firmware-sof/firmware-sof-signed_2.0-1ubuntu4.7_all.deb  404  Not Found [IP: 91.189.92.19 80]
  #7 50.31 E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
  #7 ERROR: process "/bin/sh -c apt-get update -y &&     apt-get install -y             gcc             git             make             libelf-dev linux-headers-generic linux-raspi linux-modules-extra-raspi" did not complete successfully: exit code: 100
```

This problem didn't occur in my private fork of the repo just minutes ago, where all tests passed. I'll re-run this test here.

File: src/modules/exploit_detection/syscalls/pCFI/p___queue_work/p___queue_work.c [hunk 1]
```diff
@@ -26,7 +26,13 @@ static int p_pcfi___queue_work_entry(struct kprobe *p_ri, struct pt_regs *p_regs
 
    p_ed_pcfi_cpu(0);
 
-   if (!in_irq() && p_is_ed_task(current)) {
+   if (
+#if !defined(in_hardirq) && defined(in_irq)
```
Comment (Adam-pi3) [inline src/modules/exploit_detection/syscalls/pCFI/p___queue_work/p___queue_work.c:30]: Why not the same logic as below?
#if LINUX_VERSION_CODE >= KERNEL_VERSION(6, 19, 0)

Comment (solardiz) [reply src/modules/exploit_detection/syscalls/pCFI/p___queue_work/p___queue_work.c:30]: Because `in_irq` has been obsolete for many years, so it's not good to use it when we don't have to.

Comment (solardiz) [reply src/modules/exploit_detection/syscalls/pCFI/p___queue_work/p___queue_work.c:30]: Alternatively, we could use `hardirq_count` regardless of kernel version, but this may be not as descriptive and not as future-proof (maybe the definition of `in_hardirq` will change).

Comment (Adam-pi3) [reply src/modules/exploit_detection/syscalls/pCFI/p___queue_work/p___queue_work.c:30]: Sure but per my understanding of the commit `in_irq` symbol may stay even longer in distro kernels. That being said, I don't have preferences just curious and we can use it as is.
